import Header from '@/components/header'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Provider from './theme/provider'

const nunito_sans = Nunito_Sans({ subsets: ['latin'], weight: ['300', '600', '800'] })

export const metadata = {
  title: 'Rest Countries',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  

  return (
    <html lang="en">
      <body
        className={nunito_sans.className}>
        <Provider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className='bg-very-light-gray-bg dark:text-white dark:bg-very-dark-blue-bg text-very-dark-blue-light-text min-h-screen min-w-[375px]'>
            <div className='max-w-[1320px] min-w-[375px]  mx-auto h-full px-[40px] md:px-[20px]'>
              {children}
            </div>
          </main>
        </Provider>
      </body>
    </html>
  )
}
